# NUMPY: Package for multidimensional array

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6])

In [3]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
nested_list=[[1,2,3],[4,7,8]]
sample_matrix=np.array(nested_list)

In [6]:
sample_matrix

array([[1, 2, 3],
       [4, 7, 8]])

In [15]:
np.arange(1,10) #arange

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.zeros(5)    #by default data type is float

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros(5,int) #specifying datatype

array([0, 0, 0, 0, 0])

In [20]:
#shift+tab ->help or describe the syntax

In [22]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
np.zeros((3,3),int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [37]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [38]:
np.linspace(5,20,3)

array([ 5. , 12.5, 20. ])

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.random.rand(3,2)  #beween 0 and 1

array([[0.65244421, 0.79909584],
       [0.0171747 , 0.90650062],
       [0.84192283, 0.80036459]])

In [41]:
np.random.randn(3,2)   #-ve are also inc

array([[-1.72402638,  1.27270828],
       [-0.52692292,  1.1522809 ],
       [ 1.57386966,  0.8358548 ]])

In [48]:
np.random.randint(1,17) #any random number of int datatype laying between 1 and 17

15

In [49]:
np.random.randint(1,17)  #17 is not included

13

In [60]:
arr=np.arange(50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [73]:
arr.T

array([24, 69, 86, 50, 60, 98, 15, 16, 86, 67, 82, 18, 47, 25, 71, 22, 54,
       98, 39, 74, 20, 25, 30,  9, 56, 69, 64, 27, 88,  0, 84, 46, 58, 98,
       67,  2, 84, 73, 59, 24, 87, 81,  2,  0, 59, 82, 11, 58, 76, 90])

In [74]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [75]:
rand_array=np.random.randint(0,100,20)
rand_array

array([96, 52, 38, 73, 99, 72, 14, 46, 37, 66, 65, 23, 33, 49, 61, 79, 27,
       50, 60, 54])

In [78]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [79]:
sample_array.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [80]:
sample_array.min()

0

In [81]:
rand_array.min()

14

In [82]:
rand_array.argmin() #index of the minimum value

6

In [83]:
a=np.eye(5)

In [84]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [85]:
a=np.random.rand(2,3)

In [86]:
a

array([[0.22561298, 0.85416146, 0.82946081],
       [0.29519751, 0.95575593, 0.87767682]])

In [87]:
a.T

array([[0.22561298, 0.29519751],
       [0.85416146, 0.95575593],
       [0.82946081, 0.87767682]])

In [91]:
new_arr=np.arange(15,31)

In [92]:
new_arr

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [93]:
new_arr[3:7]

array([18, 19, 20, 21])

In [95]:
new_arr[2:5]=100
new_arr

array([ 15,  16, 100, 100, 100,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30])

# TWO DIMENSION ARRAY

In [96]:
import numpy as np

In [97]:
next_array=np.array([[12,56,34,98],[29,98,56,76],[74,34,21,56]])

In [98]:
next_array

array([[12, 56, 34, 98],
       [29, 98, 56, 76],
       [74, 34, 21, 56]])

In [103]:
next_array[0:2,2] #row 0 and 1 , whose column 2

array([34, 56])

In [100]:
next_array[2,2]

21

In [101]:
next_array[2,0]

74

In [102]:
next_array[2,:]

array([74, 34, 21, 56])

In [104]:
next_array[2]

array([74, 34, 21, 56])

In [105]:
next_array[:,2]

array([34, 56, 21])

In [111]:
next_array[:,(3,2)] 
#this will print column 3rd and second for all rows in the given order

array([[98, 34],
       [76, 56],
       [56, 21]])

In [109]:
next_array[:,3]

array([98, 76, 56])

In [113]:
next_array+next_array

array([[ 24, 112,  68, 196],
       [ 58, 196, 112, 152],
       [148,  68,  42, 112]])

In [128]:
neww_array=np.array([[1,2,3,4],[11,12,13,14],[21,22,23,24]])

In [130]:
next_array+neww_array #shapes sjould be same i.e here (4,4), 4 rows,4colums

array([[ 13,  58,  37, 102],
       [ 40, 110,  69,  90],
       [ 95,  56,  44,  80]])

In [131]:
np.exp(next_array)

array([[1.62754791e+05, 2.09165950e+24, 5.83461743e+14, 3.63797095e+42],
       [3.93133430e+12, 3.63797095e+42, 2.09165950e+24, 1.01480039e+33],
       [1.37338298e+32, 5.83461743e+14, 1.31881573e+09, 2.09165950e+24]])

In [132]:
np.log(next_array)

array([[2.48490665, 4.02535169, 3.52636052, 4.58496748],
       [3.36729583, 4.58496748, 4.02535169, 4.33073334],
       [4.30406509, 3.52636052, 3.04452244, 4.02535169]])

In [133]:
np.sqrt(next_array)

array([[3.46410162, 7.48331477, 5.83095189, 9.89949494],
       [5.38516481, 9.89949494, 7.48331477, 8.71779789],
       [8.60232527, 5.83095189, 4.58257569, 7.48331477]])

In [134]:
np.min(next_array)

12

In [135]:
np.max(next_array)

98

In [136]:
np.argmin(next_array)

0

In [137]:
np.argmax(next_array)

3

In [138]:
np.std(next_array)

27.454001934549034

In [139]:
np.var(next_array)

753.7222222222222

In [140]:
np.mean(next_array)

53.666666666666664

In [152]:
np.square(next_array)

array([[ 144, 3136, 1156, 9604],
       [ 841, 9604, 3136, 5776],
       [5476, 1156,  441, 3136]])

In [156]:
np.unique(next_array)

array([12, 21, 29, 34, 56, 74, 76, 98])

In [141]:
np.round(next_array,decimals=4)

array([[12, 56, 34, 98],
       [29, 98, 56, 76],
       [74, 34, 21, 56]])

In [154]:
a=np.random.randn(3,3)
a

array([[-0.30354752,  0.09670661, -0.59320789],
       [-0.51842294, -1.10568918, -1.34547194],
       [-0.83813119,  1.52070673, -0.46254976]])

In [155]:
np.round(a,decimals=1)

array([[-0.3,  0.1, -0.6],
       [-0.5, -1.1, -1.3],
       [-0.8,  1.5, -0.5]])

In [157]:
np.round(a,decimals=3)

array([[-0.304,  0.097, -0.593],
       [-0.518, -1.106, -1.345],
       [-0.838,  1.521, -0.463]])